"""add language to posts

Revision ID: 470fc3544006
Revises: 79854d2ee955
Create Date: 2024-12-18 10:22:42.247097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470fc3544006'
down_revision = '79854d2ee955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
